#!/usr/bin/env php
<?php
namespace test;

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use test\user\Developer;

$application = new Application();
$application->add(new Developer());
var_dump(new Developer());
exit;
$application->run();

